#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
BRANCH=$1
#-------------------------- END: Settings --------------------------------


#-------------------------- Functions --------------------------------


# Install site
site_install ()
{

	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	if [[ "$BRANCH" == "master" ]]; then
	    echo "Create site"
	    drush sql-create -y
    	php -d sendmail_path=/bin/true /usr/local/bin/drush site-install demo_umami -y --site-name='My Drupal 8 Site'
	else
	    echo "Create site from demo-drupal.master"
	    drush sql-sync @demo-drupal.master @self -y
	fi

}


#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------
echo "Waiting 10s for MySQL to initialize...";
sleep 10

# Project initialization steps
time site_install


#-------------------------- END: Execution --------------------------------
